### ISSUE TITLE
wrong description for directories possible

### ISSUE THREAD

**Issue by DavidBruchmann** [usrz/autoindex#2]
Assumed there are folders like mydomain.com and also files like myfile.com I never found a way how to separate the assignment of the description for these two cases.

This case is not covered by the current existing configuration of this project, so additional configuration is required.
Furthermore the configuration has to be done with AddDescription to see and reproduce the problem, as configuration with  AddDescriptionByType works different.
Having many different file-suffixes configured it's quite often that this case occurs, so there would be a general approach nice, instead of concentrating on one special case.

As example this line can be used:
AddDescription    "com-file" .com

**Comment by pfumagalli** [comment]
I don't know if `mod_autoindex` supports `^^DIRECTORY^^` in `AddDescription` like `AddIcon` does. The documentation is here https://httpd.apache.org/docs/2.4/mod/mod_autoindex.html but this is not relevant to my config.

**Comment by DavidBruchmann** [comment]
Yeah thanks, I thought perhaps you have a solution.
I checked it again and surly knew the manual-page already but again got the impression that the module is pretty stupid and the described problem can't be solved with it.
Will try the perl-modul for autoindex, probably that's better and I expect it can also handle regular expressions for all cases, not only for exclusions like mod_autoindex does.
